### ISSUE TITLE
Serial client does not work, and example is wrong

### ISSUE THREAD

**Issue by haakonnessjoen** [biancode/node-modbus#1]
Hi,

The example in the readme has flaws, where it uses strings for things like baud rate, which your library wont allow. So it won't run without changing a lot.

I tried the client example in github (with a few modifications for my own environment):
```
var ModbusClient = require('node-modbus');
var client = ModbusClient.createSerialClient('/dev/ttyAMA0', 115200)

client.on('connect', function () {
  client.log("Connected");
  client.readInputRegister(0x000E, 2).then(function (resp) {
    console.log(resp)
  }).fail(function (err) {
    console.log(err)
  }).done(function () {
    client.close()
  })
})

client.on('error', function (err) {
  console.log(err)
})
```

But this gives me the following:
```
INFO : ModbusClientTCP log level: debug
DEBUG : ModbusClientTCP set on send method
DEBUG : ModbusClientTCP serialport settings: {"baudRate":115200,"autoOpen":true,"parity":"none","xon":false,"xoff":false,"xany":false,"rtscts":false,"hupcl":true,"dataBits":8,"stopBits":1,"bufferSize":65536,"lock":true,"platformOptions":{"vmin":1,"vtime":0}}
```

And it never runs the connect event..

I also cannot see where I specify the ID of the modbus device I want to read data from?

**Comment by biancode** [comment]
please use [modbus-serial](https://www.npmjs.com/package/modbus-serial) instead - node-modbus isn't supported anymore for now and will move to modbus-serial code state

**Comment by synatree** [comment]
Wow, maybe make that note in your README.
