### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by robertsLando** [biancode/node-modbus#12]
Is there any documentation about this package? 
I would like to know all client methods/events. Is there any method like client.isConnected() to know if the client is connected instead of make all reads inside the on 'connect'? 
Is there a way to provide a queue of reads?

**Comment by biancode** [comment]
I am sorry, there is no more documentation - just code.

**Comment by biancode** [comment]
new from v4.2.1 see the auto generated docs
<img width="446" alt="grafik" src="https://user-images.githubusercontent.com/4369867/35938422-56f1d03e-0c49-11e8-8afe-4be415663860.png">
