### ISSUE TITLE
support for long and float data ? 

### ISSUE THREAD

**Issue by bluetiger30** [biancode/node-modbus#14]
Hi , 
this is a great package, however, it doesn't display the correct value it if data sent from the Modbus device is a float or a long 
I'm using this command to read the data 
`        client.readHoldingRegisters(0, 11).then((response) => console.log(response.register))
`
if the data sent was 245 as a float it detects it as 17269 , and if is a long int it detects it as 0

**Comment by i6monitor** [comment]
the register `response.register ` is in integer/unsigned integer type.
You can use `response.buffer` for your specific application.
Refer to [Node Buffer Doc](https://nodejs.org/api/buffer.html) for more data type.

**Comment by biancode** [comment]
see [Buffer and Modbus](https://github.com/biancode/node-red-contrib-modbus/wiki/Buffer-8Bit,-16Bit,-32Bit,-64Bit,-128Bit-...-reading-with-SDM630-power-meter)

**Comment by biancode** [comment]
otherwise try the [modbus-serial-and-tcp-lib](https://github.com/yaacov/node-modbus-serial) from yaacov

**Comment by bluetiger30** [comment]
Thanks @i6monitor and @biancode . the main reason why I was getting a zero when the data was long is that because i was doing this : `client.readHoldingRegisters(0, 11)` but when I only read the address that contains the long it gives me the correct result `client.readHoldingRegisters(0, 11)`

I just have one final question , how can I read from 2 slaves at the same time on TCP ? is that possible? because I tried the follwoing by defining 2 clients :
```
const client = node_modbus.client.tcp.complete({
    'host': '192.168.1.81', //IP or name of server host 
    'port': 502, //well known Modbus port
    'unitId': 1,
    'timeout': 2000, //2 sec 
    'autoReconnect': true, //reconnect on connection is lost 
    'reconnectTimeout': 15000, //wait 15 sec if auto reconnect fails to often 
    'logLabel': 'ModbusClientTCP', //label to identify in log files 
    'logLevel': 'error', // for less log use: info, warn or error 
    'logEnabled': true
})
const client2 = node_modbus.client.tcp.complete({
    'host': '192.168.1.81', //IP or name of server host 
    'port': 502, //well known Modbus port
    'unitId': 2,
    'timeout': 2000, //2 sec 
    'autoReconnect': true, //reconnect on connection is lost 
    'reconnectTimeout': 15000, //wait 15 sec if auto reconnect fails to often 
    'logLabel': 'ModbusClientTCP', //label to identify in log files 
    'logLevel': 'error', // for less log use: info, warn or error 
    'logEnabled': true
})

const time_interval = 1000
client.connect();
client2.connect();
client.on('connect', function () {
    setInterval(function () {
        console.log("Device 1")
        client.readHoldingRegisters(11, 1).then((response) => console.log(response))
    }, time_interval) //reading coils every second 
})
client2.on('connect', function () {
    setInterval(function () {
        console.log("Device 2")

        client.readHoldingRegisters(11, 1).then((response) => console.log(response))
    }, time_interval) //reading coils every second 
})
```
but  keep getting this error : 
```
Device 1
Device 2
Unhandled rejection (<{"err":"modbus client not in \"ready\"...>, no stack trace)
```

**Comment by i6monitor** [comment]
@biancode i'm sorry published other repo here, you free to delete this.
@bluetiger30 try [i6-driver-modbus](https://github.com/annlumia/i6-driver-modbus). This is not in good maintenance. but it could be an example to start. This module base on [node-modbus](https://github.com/biancode/node-modbus)
