### ISSUE TITLE
Prevent server crash on 0 length PDU

### ISSUE THREAD

**Issue by zxlin** [biancode/node-modbus#16]
https://github.com/biancode/node-modbus/blob/master/src/modbus-server-core.js#L53

In the server core code, there's a small issue if the server receives empty data, causing `pdu` to simply be a `Buffer` of size 0 which would cause the `readUInt8(0)` call to throw a `RangeError` with the message: `index out of range` and subsequently crashing the process.

This was observed by running the server on any port and running `nmap 127.0.0.1 -p 502 -A`. 

`nmap` is a very popular port scanning tool in the network security community and as a part of its scanning script, it may sometimes send little to zero data to see how the service reacts.

Current:
```javascript
let fc = pdu.readUInt8(0)
```

Proposed:
```javascript
let fc = pdu.length > 0 ? pdu.readUInt8(0) : someDefaultValueLikeZero
```

**Comment by biancode** [comment]
please use 

https://www.npmjs.com/package/modbus-serial

or

https://www.npmjs.com/package/jsmodbus
