### ISSUE TITLE
error when try to read holding registers

### ISSUE THREAD

**Issue by cpfarher** [biancode/node-modbus#17]
Hello, I try with this example (Try to connect and read holding registers from address 0 to 10): https://gist.github.com/cpfarher/a97aa614b9cf11743e29d2a7430e8610

This is the output: 
npm run-script main

> test-modbus-serial@1.0.0 main /home/chris/test-modbus-serial
> node main.js

INFO : ModbusClientSerial log level: debug
DEBUG : ModbusClientSerial set on send method
DEBUG : ModbusClientSerial serialport settings: undefined

node: 8.11.3
 "node-modbus": "^4.3.0"

**Comment by biancode** [comment]
please use 

https://www.npmjs.com/package/modbus-serial

or

https://www.npmjs.com/package/jsmodbus
