### ISSUE TITLE
Modbus - Node v8 Support

### ISSUE THREAD

**Issue by KamalAman** [biancode/node-modbus#4]
Currently, node-modbus has a hard specification which version of node.js it supports: "node": "6.x" in its package.json. This is very limiting. 

Can you add node v8 support or change the version to `>6.x`

**Comment by biancode** [comment]
That limitation is because of serialport.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by biancode** [comment]
It will change with the LTS of v8.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
