### ISSUE TITLE
Autoreconnect example crashes if read unsuccesful

### ISSUE THREAD

**Issue by sirockin** [biancode/node-modbus#6]
`/examples/tcp/AutoReconnect.js`  - call to `fail` at line 30 needs to be replaced by `catch`

**Comment by biancode** [comment]
What about a pull request? Do you need help to work with pull-requests?

**Comment by sirockin** [comment]
Are you being deliberately abstruse, patronising or rude? I've logged an issue which you may or may not choose to log as a bug. I'll be happy to attempt a pull request once I get a reasonable response from you.

**Comment by biancode** [comment]
I do not understand, why my questions are rude. These are normal questions if I do not know anything about your skills. It is a tiny problem with an example here, and I tried to find out, why you did not contribute if you know precisely what is to do.

**Comment by sirockin** [comment]
Sorry, it's late and I'm tired and I misunderstood the issue you're replying to. Yes I'll be happy to submit a pull request on this. I'm not a nodejs expert so I wasn't certain that the catch() handler was the intendend way to deal with this but I'll assume for now it is.

**Comment by sirockin** [comment]
One more question - should the example code run unaltered from the repository? The only way I can get it to run from anywhere is to install the repo then alter the `var modbus = require('../../')` line to read `var modbus = require('node-modbus')`. If you can give me an answer on this I'll happily work through the examples, correct them and submit a pull request.

**Comment by biancode** [comment]
Yes, you could change it to have a new default, but please write a comment for developers to switch the require if they want to test without installing.
Thank you and happy coding!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sirockin** [comment]
Okay PR submitted. I've let the include as-is because I realised the examples aren't actually installed with the package.
