### ISSUE TITLE
endianType has no effect in Tcp Client

### ISSUE THREAD

**Issue by sirockin** [biancode/node-modbus#7]
Client options appear to include an 'endianType' member which defaults to "LITTLE" (modbus-client-core,js, lines 42 & 43).

This is referenced in modbus-serial-client.js but not in modbus-tcp-client.js. It appears that the behavour for a Tcp Client is always big-endian irrespective of the value of endianType.

**Comment by biancode** [comment]
Hi, are you familiar with Modbus TCP?

**Comment by biancode** [comment]
please, [check this one](https://github.com/Cloud-Automation/node-modbus)

**Comment by sirockin** [comment]
Yes I've been a system integrator for 15 years. What is the point of your question? It doesn't seem very polite.

**Comment by biancode** [comment]
Just for my interest, how technical I could answer your questions. ;)

**Comment by sirockin** [comment]
Okay, I'm just not clear on why you're pointing me to another repo (I know it's the one yours is forked from). Your answer suggests I don't understand how a Modbus TCP client should behave and perhaps the misunderstanding is mine.

So here is my understanding of the issue: 

When a modbus server exposes a value of greater than 16 bits (say a 32 bit floating point number) it is up to the implementer to decide whether the first register contains the most significant word (big-endian) or the least (little-endian).

I'm reading from a server (Wago 880 PLC) which maps these values little-endian, but the buffer I'm reading back seems to be in the opposite order suggesting that the client is remapping the bytes.  So searching through your code, I saw that the base client class* reads an endianType option which defaults to 'LITTLE'. It also seems that this value is not picked up in the TCP client subclass and assumed it was something to do with this. Am I wrong? 

*Yes I know these aren't really super and sub-classes but they act like them don't they?

**Comment by biancode** [comment]
OK. If that is also in the original repo, then please fix it there and let me know if it is done. I’ll merge it later. I asked for your skills - now the why - now I can please you to describe the problem to the original author ;)  - you could link the authors name to this issue with an annotation or just copy the comment before to the other repo, please. I am here to help, so it is all fine ;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sirockin** [comment]
Okay no problem. Out of interest, what is the reason for you maintaining a separate fork?

**Comment by sirockin** [comment]
endianType does not seem to be defined in the original at all and from reading some of the issues (eg [#114](https://github.com/Cloud-Automation/node-modbus/issues/114) it seems as if it defaults big endian (I haven't had a chance to compare though). I can't see from your repo history when the endianType option was introduced.

**Comment by biancode** [comment]
That repo is a separate fork because it is a merge of different repositories and ideas to combine the best of some. OK if it is not in the original, then I have to check.

**Comment by sirockin** [comment]
I don't mind working on a PR for this at some point but if you could find out the history of the flag, that may be useful.

**Comment by biancode** [comment]
The LITTLE was for my China Modbus serial device and I started to test with that a bit ...

**Comment by biancode** [comment]
<img width="966" alt="grafik" src="https://user-images.githubusercontent.com/4369867/35936801-9c3e4bc2-0c44-11e8-9116-0a9a517f5434.png">

it is just to control ASCII end of lines
