### ISSUE TITLE
Use node-modus on mobile with ionic

### ISSUE THREAD

**Issue by tucano** [biancode/node-modbus#9]
Hello, it is possible to use this library to connect to an industrial machine from a mobile phone?

I am building an App using Ionic2 framework

Thanks and Best Regards

**Comment by biancode** [comment]
Hello, yes sure, but use the [modbus-serial](https://github.com/yaacov/node-modbus-serial) library, please.

**Comment by sujai1009** [comment]
Hi @tucano  did you happen to build a ionic mobile app with modbus serial capability. If so can you please share some code snippets
